# Generated by Django 3.2.5 on 2021-09-02 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Missing_person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('First_Name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('eyecolor', models.CharField(choices=[('GRN', 'GREEN'), ('BLU', 'BLUE'), ('BLK', 'BLACK'), ('BRN', 'BROWN'), ('HZL', 'HAZEL'), ('OTR', 'OTHER')], default='BLK', max_length=3)),
                ('haircolor', models.CharField(max_length=200)),
                ('height_ft', models.SmallIntegerField()),
                ('height_in', models.SmallIntegerField()),
                ('weight', models.IntegerField()),
                ('description_of_disappearance', models.CharField(max_length=1000)),
                ('last_seen_latitude', models.FloatField()),
                ('last_seen_longitude', models.FloatField()),
                ('photo', models.ImageField(upload_to='cars')),
            ],
        ),
    ]
