# Generated by Django 3.2.5 on 2021-09-07 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missing_persons', '0003_auto_20210907_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(choices=[('WHITE', 'WHITE'), ('AMERICAN INDIAN OR ALASKA NATIVE', 'AMERICAN INDIAN OR ALASKA NATIVE'), ('BLACK', 'BLACK'), ('ASIAN', 'ASIAN'), ('OTHER PACIFIC ISLANDER', 'OTHER PACIFIC ISLANDER'), ('MULTIRACIAL', 'MULTIRACIAL'), ('OTHER', 'OTHER'), ('NATIVE HAWAIIAN', 'NATIVE HAWAIIAN')], max_length=70)),
            ],
        ),
        migrations.AlterField(
            model_name='eyecolor',
            name='color',
            field=models.CharField(choices=[('GREEN', 'GREEN'), ('BLUE', 'BLUE'), ('BLACK', 'BLACK'), ('BROWN', 'BROWN'), ('HAZEL', 'HAZEL'), ('OTHER', 'OTHER')], max_length=13),
        ),
        migrations.AddField(
            model_name='missing_person',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='missing_persons.race'),
        ),
    ]
