# Generated by Django 3.2.5 on 2021-09-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_persons', '0005_auto_20210910_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='missing_person',
            name='age',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
