# Generated by Django 3.2.5 on 2021-09-15 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missing_persons', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='missing_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='missing_persons.missing_person'),
        ),
    ]
