# Generated by Django 3.2.5 on 2021-09-17 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('missing_persons', '0008_alter_comment_missing_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_editted',
            field=models.DateTimeField(blank=django.utils.timezone.now, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='comment',
            name='date_published',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
